In [1]:
from itertools import combinations
from math import comb
import numpy as np

In [7]:
num_block = 8
skip_block = 2
num_combinations = comb(num_block, skip_block)
num_combinations

28

In [8]:
all_combinations = list(combinations(range(num_block), skip_block))
all_combinations

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (4, 5),
 (4, 6),
 (4, 7),
 (5, 6),
 (5, 7),
 (6, 7)]

In [9]:
masks = np.ones((len(all_combinations), num_block))
for i, idx in enumerate(all_combinations):
    masks[i, idx] = 0
print(all_combinations)

[(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 4), (3, 5), (3, 6), (3, 7), (4, 5), (4, 6), (4, 7), (5, 6), (5, 7), (6, 7)]


In [10]:
masks

array([[0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 0., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1., 0., 1., 1.],
       [0., 1., 1., 1., 1., 1., 0., 1.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [1., 0., 0., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 1.],
       [1., 0., 1., 1., 1., 0., 1., 1.],
       [1., 0., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 0., 1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 1., 0., 1., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1., 1., 1., 0.],
       [1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 0., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1., 1., 0., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 0., 1., 1.],
       [1., 1., 1., 1., 0., 1., 0., 1.],
       [1., 1., 

In [2]:
np.load("/home/zhuoyan/vision/adaptive_inference/libs/model/macs/resnet18_cifar10.npy")

array([0.15123731, 0.13619721, 0.10197149, 0.13584436, 0.10179507,
       0.13566795, 0.10170685, 0.13557974], dtype=float32)

In [3]:
np.load("/home/zhuoyan/vision/adaptive_inference/libs/model/macs/resnet18_cifar100.npy")

array([0.15123875, 0.13619699, 0.10197131, 0.13584414, 0.1017949 ,
       0.13566773, 0.10170668, 0.13557951], dtype=float32)

In [5]:
np.load("/home/zhuoyan/vision/adaptive_inference/libs/model/macs/resnet18_imagenet.npy")

array([0.2051377 , 0.12754805, 0.09549583, 0.12721762, 0.0953306 ,
       0.1270524 , 0.095248  , 0.1269698 ], dtype=float32)