In [1]:
import torch

In [2]:
masks = torch.tensor([
    [1, 0, 0, 1],  # Branch 1
    [0, 1, 1, 0],  # Branch 2
    [1, 1, 0, 0]   # Branch 3
])
is_positive = torch.tensor([
    [True, False, True],   # For Sample 1
    [False, True, False]   # For Sample 2
])
masks = masks.repeat(2, 1)
masks

tensor([[1, 0, 0, 1],
        [0, 1, 1, 0],
        [1, 1, 0, 0],
        [1, 0, 0, 1],
        [0, 1, 1, 0],
        [1, 1, 0, 0]])

In [3]:
is_positive.flatten()

tensor([ True, False,  True, False,  True, False])

In [4]:
masks[is_positive.flatten()]   

tensor([[1, 0, 0, 1],
        [1, 1, 0, 0],
        [0, 1, 1, 0]])

In [6]:
masks*torch.tensor([1,2,3,4])

tensor([[1, 0, 0, 4],
        [0, 2, 3, 0],
        [1, 2, 0, 0],
        [1, 0, 0, 4],
        [0, 2, 3, 0],
        [1, 2, 0, 0]])

In [1]:
import os
os.chdir("/home/zhuoyan/vision/adaptive_inference")
import argparse

import yaml
import torch
import torch.nn as nn
# from torch.utils.tensorboard import SummaryWriter

from libs.core import load_config
from libs.datasets import make_dataset, make_data_loader
from libs.model import Worker
from libs.utils import *

/home/zhuoyan/miniconda3/envs/vision/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
worker = Worker()

TypeError: Worker.__init__() missing 1 required positional argument: 'model_cfg'