In [1]:
import torch

In [2]:
masks = torch.tensor([
    [1, 0, 0, 1],  # Branch 1
    [0, 1, 1, 0],  # Branch 2
    [1, 1, 0, 0]   # Branch 3
])
is_positive = torch.tensor([
    [True, False, True],   # For Sample 1
    [False, True, False]   # For Sample 2
])
masks = masks.repeat(2, 1)
masks

tensor([[1, 0, 0, 1],
        [0, 1, 1, 0],
        [1, 1, 0, 0],
        [1, 0, 0, 1],
        [0, 1, 1, 0],
        [1, 1, 0, 0]])

In [3]:
is_positive.flatten()

tensor([ True, False,  True, False,  True, False])

In [4]:
masks[is_positive.flatten()]   

tensor([[1, 0, 0, 1],
        [1, 1, 0, 0],
        [0, 1, 1, 0]])

In [6]:
masks*torch.tensor([1,2,3,4])

tensor([[1, 0, 0, 4],
        [0, 2, 3, 0],
        [1, 2, 0, 0],
        [1, 0, 0, 4],
        [0, 2, 3, 0],
        [1, 2, 0, 0]])